### ISSUE TITLE
UserStoreBase-获取Claim错误

### ISSUE THREAD

**Issue by rocklee2015** [gmf520/osharp-v4#25]
UserStoreBase 类中GetClaimsAsync方法出错！
![ef](https://cloud.githubusercontent.com/assets/10364972/12001895/a36defda-ab2d-11e5-8553-5377c410de83.png)

EF,查询时只支持基元类型的查询；

**Comment by gmf520** [comment]
3.4.11版本已修复此问题，只要在UserStoreBase的主键类型中添加IEquatable<TKey>限制就行，比如
TUserKey : IEquatable<TUserKey>
